### ISSUE TITLE
Can't diff AARs that target on Java 17

### ISSUE THREAD

**Issue by Goooler** [JakeWharton/dex-method-list#119]
👋 Any idea if this will support analysing binaries built with (and targeting) JDK 17?
We currently have the following error:

```
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 61
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:9)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:1)
        at com.jakewharton.diffuse.Class$Companion.parse(Class.kt:2)
        at com.jakewharton.diffuse.Jar$Companion.parse(Jar.kt:12)
        at com.jakewharton.diffuse.Aar$Companion.parse(Aar.kt:4)
        at com.jakewharton.diffuse.InfoCommand.run(diffuse.kt:10)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:5266)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:5274)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:281)
        at com.jakewharton.diffuse.Diffuse.main(diffuse.kt:23324)
```

It seems like the asm dependency was updated

```diff
- org.ow2.asm:asm:9.3
+ org.ow2.asm:asm:9.5
```

_Originally posted by @SimonMarquis in https://github.com/JakeWharton/diffuse/issues/116#issuecomment-1513024531_

**Comment by Goooler** [comment]
I can repro it with the build artifact from 2ac9957ef89901247e6fccd8a5847413378c47b2:

```sh
chmod +x diffuse-0.2.0-SNAPSHOT-binary.jar

./diffuse-0.2.0-SNAPSHOT-binary.jar diff --aar adapter-debug.aar base-debug.aar
Exception in thread "main" java.lang.UnsupportedOperationException: PermittedSubclasses requires ASM9
    at com.jakewharton.diffuse.format.DeclaredMembersVisitor.visitPermittedSubclass(SourceFile:281)
    at org.objectweb.asm.ClassReader.accept(SourceFile:706)
    at com.jakewharton.diffuse.format.Class$Companion.parse(SourceFile:33)
    at com.jakewharton.diffuse.format.Jar$Companion.parse(SourceFile:26)
    at com.jakewharton.diffuse.format.Aar$Companion.parse(SourceFile:29)
    at com.jakewharton.diffuse.DiffCommand.run(SourceFile:173)
    at com.github.ajalt.clikt.parsers.Parser.parse(SourceFile:198)
    at com.github.ajalt.clikt.parsers.Parser.parse(SourceFile:211)
    at com.github.ajalt.clikt.core.CliktCommand.parse$default(SourceFile:18)
    at com.jakewharton.diffuse.Diffuse.main(SourceFile:415)
```

_Originally posted by @Goooler in https://github.com/JakeWharton/diffuse/issues/116#issuecomment-1513399288_
